name: CI Pipeline # Give your workflow a name
on:
  push:
    branches:
      - main # Or specify the branches you want to trigger the workflow (e.g., main, develop)
  pull_request: #optional, triggers on pull requests
    branches:
      - main
jobs:
  build_and_test: # Define a job (a set of steps)
    runs-on: ubuntu-latest # Specify the virtual environment to run the job on
    steps:
      - name: Checkout code # A step to checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17 # setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission to gradlew # Make the Gradle wrapper executable
        run: chmod +x gradlew
      - name: Build with Gradle # A step to build the application
        run: ./gradlew assemble
      - name: Test with Gradle # A step to run the tests
        run: ./gradlew test
      - name: Archive artifacts #saves the jar file
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
